Assets/Scenes/Lobby.unity

Add player count, join, host (UI)

Join and Host final set

---

Assets/Scenes/Game.unity

player Ui completed

---

Assets/Script/Game_Basic_Code.cs

bug(fixed)

---

Assets/Scenes/Game.unity
Assets/Script/Game_Basic_Code.cs

completed functions are pending

fold and check_50%completed

---

Assets/Scenes/openwindow.unity

ui updated

---

Assets/DataManager.cs
Assets/Scenes/openwindow.unity
ProjectSettings/EditorBuildSettings.asset

login page backed end completed

login page backed end completed

---

Assets/PlayFabEditorExtensions/Editor/Resources/MostRecentPackage.unitypackage.meta
Assets/Script/DataManager.cs

Code only in(test)

---

Assets/OriginalCards/Clubs/Card_Club2 (1).prefab
Assets/OriginalCards/Clubs/Card_Club8.prefab
Assets/OriginalCards/Diamond/Card_Diamond2.prefab
Assets/OriginalCards/Diamond/Card_Diamond7.prefab
Assets/OriginalCards/Diamond/Card_DiamondKing.prefab
Assets/OriginalCards/Diamond/Card_DiamondQueen.prefab
Assets/OriginalCards/Heart/Card_Heart3.prefab
Assets/OriginalCards/Heart/Card_Heart9.prefab
Assets/OriginalCards/Spade/Card_Spade7.prefab
Assets/OriginalCards/Spade/Card_SpadeAce.prefab
Assets/OriginalCards/Spade/Card_SpadeKing.prefab
Assets/Scenes/Game.unity
Assets/Script/Game_Basic_Code.cs

round 1,2,3,4 card spawn completed

---

Assets/Script/DataManager.cs

updated name backend code

---

Assets/Scenes/Lobby.unity
Assets/Script/DataManager.cs
Assets/Script/LobbyBackend.cs

set to add amount variable into playfab

set to add amount variable into playfab

---

Assets/PlayFabEditorExtensions/Editor/Resources/MostRecentPackage.unitypackage.meta
Assets/Scenes/Lobby.unity

30_11_2024 bug fixed

---

Assets/Script/LobbyBackend.cs

bug fixed 20.32 30/11/2024

---

Assets/Script/LobbyBackend.cs

BugFixed 1-12-2024

---

Assets/OriginalCards/Clubs/Card_Club5.prefab
Assets/OriginalCards/Clubs/Card_Club8.prefab
Assets/OriginalCards/Clubs/Card_Club9.prefab
Assets/OriginalCards/Clubs/Card_ClubAce.prefab
Assets/OriginalCards/Clubs/Card_ClubJack.prefab
Assets/OriginalCards/Clubs/Card_ClubQueen.prefab
Assets/OriginalCards/Diamond/Card_Diamond10.prefab
Assets/OriginalCards/Diamond/Card_Diamond3.prefab
Assets/OriginalCards/Diamond/Card_Diamond4.prefab
Assets/OriginalCards/Diamond/Card_Diamond8.prefab
Assets/OriginalCards/Diamond/Card_DiamondAce.prefab
Assets/OriginalCards/Heart/Card_Heart10.prefab
Assets/OriginalCards/Heart/Card_Heart2.prefab
Assets/OriginalCards/Heart/Card_Heart4.prefab
Assets/OriginalCards/Heart/Card_Heart6.prefab
Assets/OriginalCards/Heart/Card_Heart7.prefab
Assets/OriginalCards/Heart/Card_Heart8.prefab
Assets/OriginalCards/Heart/Card_HeartQueen.prefab
Assets/OriginalCards/Spade/Card_Spade2.prefab
Assets/OriginalCards/Spade/Card_Spade9.prefab
Assets/PlayFabEditorExtensions/Editor/Resources/MostRecentPackage.unitypackage.meta
Assets/Scenes/Game.unity
Assets/Scenes/openwindow.unity
Assets/Script/CheckButton.cs
Assets/Script/Game_Basic_Code.cs

bug chech and win

---

Assets/PlayFabEditorExtensions/Editor/Resources/MostRecentPackage.unitypackage.meta
Assets/Script/Game_Basic_Code.cs

bug fix winner sellection copy past

bug fix winner sellection copy past

---

Assets/Script/DataManager.cs
Assets/Script/LobbyBackend.cs
Assets/Script/Profile.cs

bug fix profile

---

Assets/Scenes/Lobby.unity

bug fix null refernace

---

Assets/PlayFabEditorExtensions/Editor/Resources/MostRecentPackage.unitypackage.meta
Assets/Scenes/Lobby.unity
Assets/Script/DataManager.cs
Assets/Script/LobbyBackend.cs
Assets/Script/Profile.cs

13-12-2024

---

Assets/Scenes/Game.unity
Assets/Scenes/Lobby.unity
Assets/Script/AmountManager.cs
Assets/Script/LobbyManager.cs
Assets/Script/SeatArangement.cs
Assets/Script/SeatArangement.cs.meta

me seat arrange ment vishnu get data

me seat arrange ment vishnu get data

---

Assets/PlayFabEditorExtensions/Editor/Resources/MostRecentPackage.unitypackage.meta
Assets/Scenes/Game.unity
Assets/Script/SeatArangement.cs

seat arangement test 1
